### ISSUE TITLE
SSR broken with latest version 4.0.32

### ISSUE THREAD

**Issue by MichaelDurfey** [krakenjs/beaver-logger#49]
Hello,

I started getting this error once upgrading in our application. 
```js
22-1-14:17:01:27 UNHANDLEDREJECTION ReferenceError: window is not defined
    at getHTTPTransport (/Users/mdurfey/Desktop/Development/ssrnodewebtemplate/node_modules/beaver-logger/dist/beaver-logger.js:907:46)
    at new Logger (/Users/mdurfey/Desktop/Development/ssrnodewebtemplate/node_modules/beaver-logger/dist/beaver-logger.js:999:232)
```
This commit has the change that added in window reference: https://github.com/krakenjs/beaver-logger/commit/d2f8a58dee5738399b2ded048a7d3412aaf7bb00#diff-9097bfe5ae868eccdb921b5a043bd3bc4087e8aacd257640ab51f1513baae7b4R20

**Comment by ukalbhor** [comment]
SSR is broken for shoplistnodeweb as well due to the commit. @bluepnume , can you assist with fixing ?
